### ISSUE TITLE
Incompatibility with Quark Oddities backpacks

### ISSUE THREAD

**Issue by ut-64bit** [Minecraft-LightLand/Cuisine-Delight#1]
When equipped with a backpack, the user will not be able to hold or move items.
![2023-09-23_17 07 58](https://github.com/Minecraft-LightLand/Cuisine-Delight/assets/83690503/424bea20-2bac-476e-ac7b-d5bde916381b)

**Comment by lcy0x1** [comment]
You can disable tabs in client config
