### ISSUE TITLE
Crash with BiggerAE2

### ISSUE THREAD

**Issue by WhitePhant0m** [Minecraft-LightLand/Cuisine-Delight#10]
Sorry if this isn't the correct place to report this to, but I wasn't entirely sure which mod to report this to, so I reported to both.
Crash occurs when Cuisine Delight and BiggerAE2 are both present in an instance.
Both mods work fine when the other isn't present.

[latest.log](https://mclo.gs/gYMHJJZ)
[crash log](https://mclo.gs/Ld4l68A)

https://github.com/DancingSnow0517/BiggerAE2/issues/17

**Comment by lcy0x1** [comment]
Try if CuisineDelight 1.2.1 fix the issue. Even though I did not do anything related to it, just try it out in case it works

**Comment by WhitePhant0m** [comment]
Just tested, still happens

**Comment by WhitePhant0m** [comment]
fixed by BiggerAE2
