### ISSUE TITLE
Vegetable Pasta broken recipe

### ISSUE THREAD

**Issue by FrijDom** [Minecraft-LightLand/Cuisine-Delight#2]
The Vegetable Pasta dish has the exact same requirements as the Seafood Pasta, requiring 40+% pasta and 30+% *seafood* rather than vegetables, making it impossible to make Vegetable Pasta; It will always result in Mixed Pasta.

**Comment by lcy0x1** [comment]
seems like mistake in datagen. will fix

**Comment by lcy0x1** [comment]
finished
