### ISSUE TITLE
Changes in data/[namespace]/cuisinedelight_config/ingredient/ have no effect

### ISSUE THREAD

**Issue by spad4** [Minecraft-LightLand/Cuisine-Delight#5]
I'm making a modpack, and I'd like to add additional compatibility between some of the mods I'm using (namely Alex's mobs) and Cuisine Delight. I've tried making modifications to the files in `data/cuisinedelight/cuisinedelight_config`, but they don't have any effect on what can be cooked. I've tried copying the entire file tree (starting at the `cuisinedelight` namespace) into the `data` folder, and then making changes from there (such as removing carrots from `./vege.json`). Restarting Minecraft doesn't work either. Is it supposed to be possible to change ingredients using datapacks?

**Comment by lcy0x1** [comment]
Sorry for late reply. It should work and multiple people have it working already. Join discord for further discussion.

**Comment by spad4** [comment]
Oh cool, thanks so much. I'll be sure to check it out.
